### PR TITLE
Added option to CMakeLists.txt to disable VST plugin compilation.

### PR DESCRIPTION
**Pull request by LeStahL**
This allows coders to disable the VST plugin compilation completely.

### CODE REVIEW

**Comment by yupferris** [comment]
This looks good, but I don't like the double-negative - can we make a default-truthy `BUILD_VST_PLUGINS` variable instead? (same with #96)

**Comment by yupferris** [comment]
Also needs conflict resolution after merging #93.

**Comment by LeStahL** [comment]
Rebased and removed double negation.

**Comment by yupferris** [comment]
cheers!

**Pull request merged**
